force-app/main/default/objects/Account/fields/MSA_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>MSA_Document_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>MSA Document Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/MSA_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>MSA_Document_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>MSA Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NDA_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>NDA_Document_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>NDA Document Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/NDA_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>NDA_Document_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>NDA Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ZohoWebhookHandler.cls
@RestResource(urlMapping='/api/Webhooks/ZohoWebhookHandler/*')
global without sharing class ZohoWebhookHandler {
    
    // Method to handle POST request
    @HttpPost
    global static void handlePost() {
        
        RestResponse res = RestContext.response;

        // Get the request body data
        String requestBody = RestContext.request.requestBody.toString();

        ZohoWebhookWrapper wrapper = (ZohoWebhookWrapper)JSON.deserialize(requestBody, ZohoWebhookWrapper.class);
        
        if(wrapper != NULL) {
          
            List<Account> accListToUpd = new List<Account>();
            if(wrapper.requests.document_ids[0].document_name != NULL && wrapper.requests.document_ids[0].document_name == 'NDA FEXLE') {
                
                String ndaDocumentId = wrapper.requests.document_ids[0].document_id;
                accListToUpd = [SELECT NDA_Document_Id__c,NDA_Document_Status__c FROM Account WHERE NDA_Document_Id__c =:ndaDocumentId LIMIT 1];
                accListToUpd[0].NDA_Document_Status__c = 'Signed';
            } 
            else if(wrapper.requests.document_ids[0].document_name != NULL && wrapper.requests.document_ids[0].document_name == 'Vendor Agreement - Draft') {
                 
                String msaDocumentId = wrapper.requests.document_ids[0].document_id;
                accListToUpd = [SELECT MSA_Document_Id__c,MSA_Document_Status__c FROM Account WHERE MSA_Document_Id__c =:msaDocumentId LIMIT 1];
                accListToUpd[0].MSA_Document_Status__c = 'Signed';
            }
            if (!accListToUpd.isEmpty()) {
                try {
                    update accListToUpd;
                } catch (DmlException e) {
                     PartnerSignupExceptionHandler.logException(e.getMessage(),e.getLineNumber(),'handlePost','ZohoWebhookHandler');
                }
           }
        }
    }
}